name: Build and Push Docker Container
on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag good-morning
    - name: Tag version
      run: docker tag good-morning ${{ secrets.DOCKER_USERNAME }}/good-morning:${{ github.event.release.tag_name }}
    - name: Tag latest
      run: docker tag good-morning ${{ secrets.DOCKER_USERNAME }}/good-morning:latest
    - name: Push Docker image to Docker Hub
      uses: docker/push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: good-morning
