name: Run tests
on:
  push:
    branches:
      - "**"

env:
  CI: true

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: "Setup Node"
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Lint"
        run: |
          npm ci
          npm run lint
      - name: "Test"
        run: |
          npm ci
          npm test
